# Builds src/toolbar.c out of the executable's own tool bar.
#
# Lord Monarch does not put words on its tool bar - it is twenty-three 16x16
# icons, which is what the user sees instead of a second row of text.  Two
# resources describe it:
#
#   type 241 id 102   the MFC RT_TOOLBAR: button size and the command number
#                     of each button, with zero for a separator
#   BITMAP 102        368x16 at 4 bits a pixel - the twenty-three icons in a
#                     row, sharing one sixteen-entry palette
#
#   python tools/make_toolbar.py ds7e.zip
import struct
import sys
import zipfile

ARCHIVE = sys.argv[1] if len(sys.argv) > 1 else 'ds7e.zip'

z = zipfile.ZipFile(ARCHIVE)
d = z.read([n for n in z.namelist() if n.upper().endswith('.EXE')][0])
pe = struct.unpack_from('<I', d, 0x3c)[0]
nsec = struct.unpack_from('<H', d, pe + 6)[0]
optsz = struct.unpack_from('<H', d, pe + 20)[0]
secs = []
off = pe + 24 + optsz
for i in range(nsec):
    e = d[off + i * 40:off + (i + 1) * 40]
    nm = e[:8].rstrip(b'\0').decode()
    vsz, va, rsz, ra = struct.unpack_from('<IIII', e, 8)
    secs.append((nm, va, vsz, ra))
rs = [s for s in secs if s[0] == '.rsrc'][0]
rva0, fa0 = rs[1], rs[3]


def at(r):
    return fa0 + (r - rva0)


def kids(o):
    o = fa0 + o
    nn, ni = struct.unpack_from('<HH', d, o + 12)
    return [struct.unpack_from('<II', d, o + 16 + i * 8) for i in range(nn + ni)]


def blob(tid, rid):
    for tname, toff in kids(0):
        if (tname & 0x7fffffff) != tid or not (toff & 0x80000000):
            continue
        for nname, noff in kids(toff & 0x7fffffff):
            if (nname & 0x7fffffff) != rid:
                continue
            for lname, loff in kids(noff & 0x7fffffff):
                o = fa0 + (loff & 0x7fffffff)
                da, sz = struct.unpack_from('<II', d, o)
                return d[at(da):at(da) + sz]
    return None


bar = blob(241, 102)
ver, cx, cy, n = struct.unpack_from('<HHHH', bar, 0)
ids = list(struct.unpack_from('<%dH' % n, bar, 8))

bmp = blob(2, 102)
# A BITMAPINFOHEADER without the file header, which is how a resource holds one.
size, w, h, planes, bpp = struct.unpack_from('<IiiHH', bmp, 0)
comp, imgsz, xppm, yppm, used, important = struct.unpack_from('<IIiiII', bmp, 16)
assert bpp == 4 and comp == 0, (bpp, comp)
colours = used if used else 16
pal = []
for i in range(colours):
    b, g, r, _ = struct.unpack_from('<BBBB', bmp, size + i * 4)
    pal.append((r, g, b))
bits = size + colours * 4
stride = ((w * 4 + 31) // 32) * 4

# Rows are bottom-up in a DIB.
pix = bytearray(w * h)
for y in range(h):
    src = bits + (h - 1 - y) * stride
    for x in range(w):
        byte = bmp[src + x // 2]
        pix[y * w + x] = (byte >> 4) if (x % 2 == 0) else (byte & 15)

out = []
out.append('// Generated by tools/make_toolbar.py - do not edit.')
out.append('//')
out.append('// The tool bar out of the executable: %d icons of %dx%d, four bits' %
           (w // cx, cx, cy))
out.append('// a pixel over one palette, and the command each button sends.')
out.append('// Lord Monarch draws no words up there at all.')
out.append('#include "toolbar.h"')
out.append('')
out.append('const int kToolbarW = %d;' % w)
out.append('const int kToolbarH = %d;' % h)
out.append('const int kToolbarButton = %d;' % cx)
out.append('const int kToolbarIcons = %d;' % (w // cx))
out.append('')
out.append('// Red, green, blue, straight out of the bitmap.  Entry %d is the'
           % 0)
out.append('// face grey the buttons sit on, which is drawn as the chrome\'s own.')
out.append('const unsigned char kToolbarPalette[%d][3] = {' % colours)
for r, g, b in pal:
    out.append('    {%3d, %3d, %3d},' % (r, g, b))
out.append('};')
out.append('')
out.append('const unsigned char kToolbarPixels[%d] = {' % (w * h))
for i in range(0, w * h, 32):
    out.append('    ' + ''.join('%d,' % v for v in pix[i:i + 32]))
out.append('};')
out.append('')
out.append('// Zero is a separator, as the resource has it.')
out.append('const unsigned short kToolbarCommand[%d] = {' % n)
for i in range(0, n, 8):
    out.append('    ' + ' '.join('%5d,' % v for v in ids[i:i + 8]))
out.append('};')
out.append('const int kToolbarButtons = %d;' % n)
out.append('')

open('src/toolbar.c', 'w', encoding='utf-8').write('\n'.join(out))
print('wrote src/toolbar.c: %d icons, %d buttons, %d colours' %
      (w // cx, n, colours))
