# -*- coding: utf-8 -*-
"""Generate src/rsrc_sjis.c: the characters the resources are written in.

    python tools/make_rsrc_text.py ds7e.zip ds7j.zip > src/rsrc_sjis.c

A Windows resource string is UTF-16, and the Japanese release's menu and
dialogs are Japanese.  Everything else in this port speaks Shift-JIS - it is
what the game's own data files are in and what src/font16.c draws - so
src/rsrc.c turns a resource string into Shift-JIS on the way out, and this is
the table it does it with.

Only the characters that actually appear in the two releases' MENU and DIALOG
resources are in it, which is about a hundred: generating it is the point,
because a table typed out by hand is the mistake this port has made before.
"""
import struct
import sys
import zipfile


def load(archive):
    z = zipfile.ZipFile(archive)
    name = [n for n in z.namelist() if n.upper().endswith('.EXE')][0]
    return z.read(name)


def strings(d):
    """Every UTF-16 string in every MENU and DIALOG resource of `d`."""
    pe = struct.unpack_from('<I', d, 0x3c)[0]
    nsec = struct.unpack_from('<H', d, pe + 6)[0]
    optsz = struct.unpack_from('<H', d, pe + 20)[0]
    base = struct.unpack_from('<I', d, pe + 24 + 28)[0]
    secs = []
    off = pe + 24 + optsz
    for i in range(nsec):
        e = d[off + i * 40:off + (i + 1) * 40]
        vsz, va, rsz, ra = struct.unpack_from('<IIII', e, 8)
        secs.append((base + va, vsz, ra, rsz))

    def fo(rva):
        for sva, vsz, ra, rsz in secs:
            if sva <= rva < sva + max(vsz, rsz):
                return ra + (rva - sva)
        return None

    root = fo(base + struct.unpack_from('<I', d, pe + 24 + 96 + 8 * 2)[0])

    def kids(o):
        named, ids = struct.unpack_from('<HH', d, o + 12)
        return [struct.unpack_from('<II', d, o + 16 + i * 8)
                for i in range(named + ids)]

    out = []
    for nm, off2 in kids(root):
        if (nm & 0x7fffffff) not in (4, 5):     # RT_MENU, RT_DIALOG
            continue
        for _, off3 in kids(root + (off2 & 0x7fffffff)):
            for _, off4 in kids(root + (off3 & 0x7fffffff)):
                rva, size = struct.unpack_from('<II', d, root + off4)
                blob = d[fo(base + rva):fo(base + rva) + size]
                # Every run of printable UTF-16 in it.  A resource is a mix of
                # strings and fixed fields, so this over-reads - which is
                # harmless: an extra character in the table costs four bytes.
                run = []
                for i in range(0, len(blob) - 1, 2):
                    w = struct.unpack_from('<H', blob, i)[0]
                    if w >= 0x20:
                        run.append(chr(w))
                    elif run:
                        out.append(''.join(run))
                        run = []
                if run:
                    out.append(''.join(run))
    return out


def main():
    archives = sys.argv[1:] or ['ds7e.zip', 'ds7j.zip']
    seen = {}
    for archive in archives:
        for text in strings(load(archive)):
            for ch in text:
                if ord(ch) < 0x80 or ch in seen:
                    continue
                try:
                    seen[ch] = ch.encode('shift_jis')
                except UnicodeEncodeError:
                    pass                        # not Shift-JIS: not the game's

    rows = sorted(seen.items(), key=lambda kv: ord(kv[0]))
    print('// Generated by tools/make_rsrc_text.py - do not edit.')
    print('//')
    print('// The characters the two releases write their menu and their')
    print('// dialogs in, as Shift-JIS, which is what the rest of this port')
    print('// speaks.  A resource string is UTF-16; src/rsrc.c walks this')
    print('// table on its way out.')
    print('#include "rsrc.h"')
    print('')
    print('const RsrcChar kRsrcChars[] = {')
    for ch, sjis in rows:
        b = ', '.join('0x%02x' % c for c in sjis)
        print('    {0x%04x, {%s, 0}},' % (ord(ch), b))
    print('};')
    print('')
    print('const int kRsrcCharCount = %d;' % len(rows))
    return 0


if __name__ == '__main__':
    sys.exit(main())
