# -*- coding: utf-8 -*-
"""Which glyphs the releases' own menus want and src/font16.c has not got.

    python tools/missing_glyphs.py ds7e.zip ds7j.zip > tools/font_extra.txt

The Japanese release writes its menu in Japanese and the port reads it out of
the executable, but the font carries only the kanji the game's own data files
use - so some of the menu cannot be drawn, and src/wasm_main.cpp keeps the
English caption where that happens.  This lists the Shift-JIS codes that would
have to be added, in the form make_font.py takes as its second argument:

    python tools/make_font.py <dir with the BDFs> tools/font_extra.txt

The BDFs are not in this repository; make_font.py's own comment says where
they come from.
"""
import io
import os
import re
import struct
import sys
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def resource_strings(archive, types=(4, 5)):
    """Every UTF-16 run in the MENU and DIALOG resources of an archive."""
    z = zipfile.ZipFile(archive)
    d = z.read([n for n in z.namelist() if n.upper().endswith('.EXE')][0])
    pe = struct.unpack_from('<I', d, 0x3c)[0]
    nsec = struct.unpack_from('<H', d, pe + 6)[0]
    optsz = struct.unpack_from('<H', d, pe + 20)[0]
    base = struct.unpack_from('<I', d, pe + 24 + 28)[0]
    secs = []
    off = pe + 24 + optsz
    for i in range(nsec):
        e = d[off + i * 40:off + (i + 1) * 40]
        vsz, va, rsz, ra = struct.unpack_from('<IIII', e, 8)
        secs.append((base + va, vsz, ra, rsz))

    def fo(rva):
        for sva, vsz, ra, rsz in secs:
            if sva <= rva < sva + max(vsz, rsz):
                return ra + (rva - sva)
        return None

    root = fo(base + struct.unpack_from('<I', d, pe + 24 + 96 + 8 * 2)[0])

    def kids(o):
        named, ids = struct.unpack_from('<HH', d, o + 12)
        return [struct.unpack_from('<II', d, o + 16 + i * 8)
                for i in range(named + ids)]

    out = []
    for nm, off2 in kids(root):
        if (nm & 0x7fffffff) not in types:
            continue
        for _, off3 in kids(root + (off2 & 0x7fffffff)):
            for _, off4 in kids(root + (off3 & 0x7fffffff)):
                rva, size = struct.unpack_from('<II', d, root + off4)
                blob = d[fo(base + rva):fo(base + rva) + size]
                run = []
                for i in range(0, len(blob) - 1, 2):
                    w = struct.unpack_from('<H', blob, i)[0]
                    if w >= 0x20:
                        run.append(chr(w))
                    elif run:
                        out.append(''.join(run))
                        run = []
                if run:
                    out.append(''.join(run))
    return out


def font_codes():
    """The Shift-JIS codes src/font16.c carries a wide glyph for."""
    text = io.open(os.path.join(ROOT, 'src', 'font16.c'),
                   encoding='utf-8').read()
    at = text.find('kFontWideCode')
    end = text.find('};', at)
    return {int(m, 16) for m in re.findall(r'0x([0-9a-fA-F]{4})',
                                           text[at:end])}


def main():
    archives = sys.argv[1:] or ['ds7e.zip', 'ds7j.zip']
    have = font_codes()
    want = {}
    for archive in archives:
        for text in resource_strings(archive):
            for ch in text:
                if ord(ch) < 0x80:
                    continue
                try:
                    sjis = ch.encode('shift_jis')
                except UnicodeEncodeError:
                    continue
                if len(sjis) != 2:
                    continue                    # half width: always present
                code = (sjis[0] << 8) | sjis[1]
                if code not in have:
                    want.setdefault(code, ch)

    print('# The wide glyphs the releases\' menus and dialogs want and')
    print('# src/font16.c has not got.  Generated by')
    print('# tools/missing_glyphs.py; feed it to make_font.py.')
    for code in sorted(want):
        print('%04x   # %s' % (code, want[code]))
    print('# %d in all' % len(want), file=sys.stderr)
    return 0


if __name__ == '__main__':
    sys.exit(main())
